### ISSUE TITLE
Mouse clicks not registered when Chromebook has a touchscreen

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#160]
Most newer Chromebooks can download the Android version of ScratchJr from the Google Play Store. The Android version is designed for tablets (touchscreen). 

If the Chromebook has a touchscreen in addition to a touchpad, ScratchJr only works with the touchscreen. Mouse clicks do not register as 'touches'.

It is confusing because the animations react to the mouse, but the application doesn't.

**Comment by joshualawson** [comment]
Noticed this on a Chromebook 11, does not register mouse clicks, would be awesome to fix this!

**Comment by manubrambi** [comment]
The problem appears also on Android devices (non-chromebook). @chrisgarrity is correct "the animations react to the mouse, but the application doesn't."

**Comment by ajanian** [comment]
I think there may be more to this issue.  I just installed the app on a Chromebook without a touchscreen and the mouse clicks don't register either.  The Chromebook is XE350XBA-K03US [at Amazon](https://www.amazon.com/gp/product/B07XL4JDQW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) or [at Samsung](https://www.samsung.com/us/computing/chromebooks/15-18/chromebook-4-15-6-64gb-storage-6gb-ram-xe350xba-k03us/)

**Comment by Bobbbay** [comment]
I see this has been added to the backlog, so I've got some potential answers here. Just opinions, of course. 

### What isn't working?
The app isn't registering mouse clicks. 

### Why isn't it working?
Here's my thesis:

Scratch Junior's Chromebook Edition is designed for Android, which is a mobile operating system. Hence scratch Junior expects input from a touch screen. Not sure if this should be regular behavior in any app, but this sounds the most plausible to me. Now, Chromebooks use Android applications natively, which I find enticing, to say the least. I think the reason is that this app simply doesn't expect mouse input, at least when compiling for Android. 

This is definitely testable by hooking up a mouse to a mobile phone, and testing if input is detected. 

Of course, could be really wrong :). 

Thoughts?

**Comment by justisGipson** [comment]
i think regardless of whether or not the chromebook has a touchscreen, the app is **always** expecting touch input. I'm going to fork and play around with this. As I need Scratch Jr to have mouse support on chromebooks

**Comment by jmbouffard** [comment]
@justisGipson I am also interested in having ScratchJr work on Chrome Books with no touchscreen, which seems to be a problem right now. Is there any workaround available at the moment? Would ARC Welder be a way to run it on a Chromebook instead of a native install? I also saw that there were plans for a web version of ScratchJr but could not find much info. Thanks.

**Comment by justisGipson** [comment]
@jmbouffard I don't know of any workaround for this. Doing some discovery into this in my free time. ARC welder seems like it would work, but as of Dec 2020 it looks like it's no longer supported... And same about the web version.

**Comment by chrisgarrity** [comment]
closing in favor of https://github.com/LLK/scratchjr/issues/222
