### ISSUE TITLE
Deleting a block pops scrollbars instead of actually removing the block

### ISSUE THREAD

**Issue by jfo8000** [LLK/scratchjr#173]
Repro steps

Open Scratch JR
Create a new project
Drag a block down to the scripts area and let go
Now drag it again and try to return it to the blocks tray

![image](https://user-images.githubusercontent.com/16273166/40883997-87b6e312-674d-11e8-88fb-ffea3deaa28c.png)

Expected:
The block deletes from the scripts area.

Actual Result:
![image](https://user-images.githubusercontent.com/16273166/40883983-39b22a00-674d-11e8-8cc4-a5a91ece41d1.png)

More info:
The problem is in getLandingPlace inside of Pallete.js
**See BOLD section for my three line bug fix.**

 // move to scratch jr app
    static getLandingPlace (el, e, scale) {
        scale = typeof scale !== 'undefined' ? scale : 1;
        var sc = ScratchJr.getActiveScript().owner;
        var pt = e ? Events.getTargetPoint(e) : null;
        if (pt && !pt.x) {
            pt = null;
        }
        var box = new Rectangle(el.left / scale, el.top / scale, el.offsetWidth / scale, el.offsetHeight / scale);
        var box2 = new Rectangle(globalx(gn('palette')), globaly(gn('palette')),
                                 gn('palette').offsetWidth, gn('palette').offsetHeight);
        if ((sc.flowCaret != null) && ((sc.flowCaret.prev != null) ||
            (sc.flowCaret.next != null) || (sc.flowCaret.inside != null))) {
            return 'scripts';
        }
        if (box2.overlapElemBy(box, 0.66) && box2.hitRect({x: el.left / scale, y: el.top / scale})) {
            return 'palette';
        }
        if (pt && box2.hitRect(pt)) {
            return 'palette';
        }
**if (Palette.overlapsWith(gn('blockspalette'), box)) { // bugfix - blockspallete should delete block
            return 'palette';
        }**
        if (Palette.overlapsWith(gn('scripts'), box)) {
            return 'scripts';
        }
        if (Palette.overlapsWith(gn('palette'), box)) {
            return 'palette';
        }
        if (Palette.overlapsWith(gn('library'), box)) {
            return 'library';
        }
        if (Palette.overlapsWith(gn('pages'), box)) {
            return 'pages';
        }
        return null;
    }

**Comment by jfo8000** [comment]
This is the most frequent source of frustration I've experienced with kindergarteners using the app because they dont drag the block high enough and get stuck in scrollworld.

**Comment by thisandagain** [comment]
Thanks for reporting!

/cc @chrisgarrity

**Comment by benjiwheeler** [comment]
I confirmed this problem. One important thing to understand is that the current handling distinguishes whether to delete the block or move it based on where the cursor/touch was initiated on the block -- if the cursor releases with the _cursor_ over the blocks palette, the block is deleted, but otherwise it is simply moved. 

That seems to be the fundamental problem; I imagine that a user would think "the _block_ is now over the blocks palette, I can release my finder to delete it", when the actual behavior is "my _finger_ is now over the blocks palette".

@jfo8000's fix looks like it would reinterpret any overlap at all of blocks over the blocks palette when the user releases their finger as making the blocks be deleted. Another way of describing this is that a block must be overlapping the blocks palette only 1% or so for it to be deleted; whereas the current code requires a variable amount, between about 1% and 100%. What is the ideal amount? My guess is that it is something more like 50%.

What if, instead of 
```
        if (Palette.overlapsWith(gn('blockspalette'), box)) { // bugfix - blockspallete should delete block
            return 'palette';
        }
```
we instead changed the `0.66` value on this line:
```
        if (box2.overlapElemBy(box, 0.66) && box2.hitRect({x: el.left / scale, y: el.top / scale})) {
            return 'palette';
        }
```
to something like:
```
        if (box2.overlapElemBy(box, 0.4) && box2.hitRect({x: el.left / scale, y: el.top / scale})) {
            return 'palette';
        }
```
?

In my testing, this allowed for blocks to be deleted, or moved upwards, in a reasonable balance.
