### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by vdurnev** [LLK/scratchjr#280]
Hi here! 

Thank you for the great app.
I would like to help with Ukrainian localization for ScratchJr.

I have translated en.json and storelisting_en.json  plus added Ukrainian to the settings.json.
Let me know if I can make a pull request to the devlelop branch with my changes.

Thank you
Vitaliy

**Comment by vdurnev** [comment]
All required changes are in these 2 commits:
https://github.com/vdurnev/scratchjr/commit/bb10895939b1f80113cf062623f68770faf8747b
https://github.com/vdurnev/scratchjr/commit/43b3e30612e7a47e99e30028c2f7dea3d168c9da

**Comment by chrisgarrity** [comment]
Sorry, @vdurnev we don't accept localization PRs because the localization is managed through the Transifex system. However, you can apply to join the translation team for ScratchJr by filling out this short form: https://forms.gle/9v1DSxHLJxMrz48G6

As part of the team you'd be able to upload new versions of the resource files. Languages are added to ScratchJr after they have been fully translated and reviewed.
