### ISSUE TITLE
Process 'command './bundle-compile.sh'' finished with non-zero exit value 127

### ISSUE THREAD

**Issue by 504254103** [LLK/scratchjr#397]
The following problems occurred after compilation.I found the address of the error file(scratchjr-develop/bin/bundle-compile.sh), but I don’t know how to modify it

**Comment by chrisgarrity** [comment]
The bundle-compile script simply builds the javascript bundle, so you should not need to edit it. If it is getting an error it is probably because you do not have one of the dependencies installed. Please make sure you have installed node and npm and run `npm install` as documented in the initialization section of the README.
